name: Deploy static site to GitHub Pages

on:
  push:
    branches: ["main"]  # or 'main' — change this if needed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # 👈 this is your static site folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
